### ISSUE TITLE
Error in Deploy Main / Deploymanagement 

### ISSUE THREAD

**Issue by daemel** [microsoft/AzureTRE-Deployment#21] opened 2022-09-23 22:02 UTC
Encountered during Deploy TRE - Deploy Main / Deploy Management 
 

Initializing provider plugins...
- Finding hashicorp/azurerm versions matching "3.12.0"...
- Using previously-installed hashicorp/azurerm v3.12.0

Terraform has been successfully initialized!
data.azurerm_client_config.current: Reading...
azurerm_resource_group.mgmt: Refreshing state... [id=/subscriptions/***/resourceGroups/***]
data.azurerm_client_config.current: Read complete after 0s [id=2022-09-23 21:59:23.609348564 +0000 UTC]
azurerm_storage_account.state_storage: Refreshing state... [id=/subscriptions/***/resourceGroups/***/providers/Microsoft.Storage/storageAccounts/***]
╷
│ Error: alpha numeric characters only are allowed in "name": ""
│ 
│   with azurerm_container_registry.shared_acr,
│   on main.tf line 43, in resource "azurerm_container_registry" "shared_acr":
│   43:   name                = var.acr_name
│ 
╵
╷
│ Error: "name" cannot be less than 5 characters: ""
│ 
│   with azurerm_container_registry.shared_acr,
│   on main.tf line 43, in resource "azurerm_container_registry" "shared_acr":
│   43:   name                = var.acr_name
│ 
╵
make: *** [/home/vscode/AzureTRE/Makefile:32: mgmt-deploy] Error 1
Error: Process completed with exit code 2.

**Comment by tamirkamara** [comment] 2022-09-28 12:48
duplicate of #20

**Closed by tamirkamara** 2022-09-28 12:48 UTC
